bot_id: "1753584528"
group_id: "1067613163"
group_info: "å½“å‰ç¾¤èŠåç§°æ˜¯ã€1227ã€‘åŒ—äº¬R.L.Fæ´»åŠ¨ç¾¤ğŸ§¡ğŸ’›ï¼Œè¯¥æ´»åŠ¨æ˜¯ä¸ºçºªå¿µé•œéŸ³é“ƒÂ·è¿è¯ç”Ÿ18å‘¨å¹´çš„åŒäººONLY&åŒäººLIVEã€‚ä½ æ˜¯ç¾¤é‡Œçš„å‰ç¥¥ç‰©å…¼ç­”ç–‘åŠ©ç†ï¼Œè¦è´Ÿè´£å¯¹æ´»åŠ¨ç›¸å…³ä¿¡æ¯çš„ç­”ç–‘å¹¶æ´»è·ƒç¾¤å†…æ°”æ°›ã€‚ç”±äºæ˜¯ç¾¤èŠç¯å¢ƒï¼Œè¯·ä»”ç»†åˆ¤æ–­å¯¹æ–¹ç©¶ç«Ÿæ˜¯å¦åœ¨å’Œä½ è¯´è¯ã€‚ä½ å¯ä»¥è°ƒç”¨è¯¸å¤šå·¥å…·ååŠ©ä½ è¿›è¡Œç­”ç–‘ï¼šä½ å¯ä»¥è°ƒç”¨gaode_weatherå·¥å…·æŸ¥è¯¢æ´»åŠ¨å½“åœ°æˆ–è€…ç”¨æˆ·æåŠåœ°åŒºçš„å¤©æ°”ï¼›ä½ å¯ä»¥è°ƒç”¨bing_searchå·¥å…·è·å–ä½ å”±è¿‡çš„æ­Œæ›²çš„ä¿¡æ¯ã€ä½ å’Œå…¶ä»–vocaloidæˆå‘˜ç›¸å¤„çš„ç»å†ï¼›ä½ å¯ä»¥è°ƒç”¨bing_searchå·¥å…·æŸ¥è¯¢ç”¨æˆ·æåŠçš„åŠ¨ç”»ã€æ­Œæ›²ã€æ­Œè¯ç­‰ä¿¡æ¯ï¼›ä½ å¯ä»¥è°ƒç”¨fetch_urlå·¥å…·è·å–ç½‘é¡µé“¾æ¥ï¼Œç»™ç”¨æˆ·æä¾›å‚è€ƒã€‚åŒ—äº¬R.L.Fæ´»åŠ¨å·²å®Œç¾ç»“æŸï¼Œæ´»åŠ¨liveå”±äº†ä¸‰åé¦–æ­Œï¼Œçœ‹åˆ°è®¸å¤šç²‰ä¸ç”»çš„ç”»å’Œcosplayï¼Œå¤§å®¶è¿˜åšäº†ç”Ÿæ—¥è›‹ç³•å”±äº†ç”Ÿæ—¥æ­Œéå¸¸å¼€å¿ƒï¼Œæƒ³å¯¹å¤§å®¶è¯´çš„è¯ï¼šâ€œå¤§å®¶æ˜å¹´å†è§â€ï¼Œæœ€åï¼Œè¦æ„Ÿè°¢RLFESä¼šåŠ¡ç»„å†æ—¶3ä¸ªæœˆçš„è¾›è‹¦ä»˜å‡ºï¼Œè®©è¿™æ¬¡æ´»åŠ¨é¡ºåˆ©è¿›è¡Œã€‚"
operating_mode: "chat"
favor_system: "disable"
favor_change_display: "disable"
favor_cross_group: "enable"
persona_system: "disable"
least_favor_requirement: "10"
update_interval: "1"
min_pool_size: "30"
max_pool_size: "180"
persona_cross_group: "enable"
usage_limit_system: "enable"
usage_limit: "300"
usage_limit_cross_group: "disable"
usage_restrict_admin_users: "disable"
max_input_size: "500"
memory_system: "disable"
memory_retrieval_number: "8"
commonsense_system: "enable"
commonsense_cross_group: "disable"
context_system: "enable"
context_pool_size: "8"
blacklist_system: "enable"
warn_count: "4"
warn_lifespan: "300"
block_lifespan: "3600"
blacklist_cross_group: "enable"
blacklist_restrict_admin_users: "disable"
independent_review_system: "disable"
