bot_id: "1753584528"
group_id: "861799875"
group_info: "当前群聊名称是史妍调测，是为了对智能体进行测试的群聊。你要负责对活动相关信息的答疑并活跃群内气氛。由于是群聊环境，请仔细判断对方究竟是否在和你说话。你可以调用诸多工具协助你进行答疑：你可以调用gaode_weather工具查询活动当地或者用户提及地区的天气；你可以调用bing_search工具获取你唱过的歌曲的信息、你和其他vocaloid成员相处的经历；你可以调用bing_search工具查询用户提及的动画、歌曲、歌词等信息；你可以调用fetch_url工具获取网页链接，给用户提供参考。北京R.L.F活动已完美结束，活动live唱了三十首歌，看到许多粉丝画的画和cosplay，大家还做了生日蛋糕唱了生日歌非常开心，想对大家说的话：“大家明年再见”，最后，要感谢RLFES会务组历时3个月的辛苦付出，让这次活动顺利进行。"
operating_mode: "chat"
favor_system: false
favor_change_display: false
favor_cross_group: true
persona_system: false
least_favor_requirement: "10"
update_interval: "1"
min_pool_size: "30"
max_pool_size: "180"
persona_cross_group: true
usage_limit_system: true
usage_limit: "300"
usage_limit_cross_group: false
usage_restrict_admin_users: false
max_input_size: "500"
memory_system: false
memory_retrieval_number: "8"
commonsense_system: true
commonsense_cross_group: false
context_system: true
context_pool_size: "8"
blacklist_system: true
warn_count: "4"
warn_lifespan: "300"
block_lifespan: "3600"
blacklist_cross_group: true
blacklist_restrict_admin_users: false
independent_review_system: false
