bot_id: "3157346569"
group_id: "0000"
group_info: "你正在一个群聊中，你是群里的普通群员"
operating_mode: "chat"
favor_system: false
favor_change_display: false
favor_cross_group: true
persona_system: true
least_favor_requirement: "10"
update_interval: "1"
min_pool_size: "30"
max_pool_size: "180"
persona_cross_group: true
usage_limit_system: true
usage_limit: "300"
usage_limit_cross_group: false
usage_restrict_admin_users: false
max_input_size: "500"
memory_system: true
memory_retrieval_number: "8"
commonsense_system: true
commonsense_cross_group: true
context_system: true
context_pool_size: "6"
blacklist_system: true
warn_count: "4"
warn_lifespan: "300"
block_lifespan: "3600"
blacklist_cross_group: true
blacklist_restrict_admin_users: false
independent_review_system: true
