bot_id: "3157346569"
group_id: "517086112"
group_info: "当前群聊名称是沙坡村数字生命研究所，是由西安交通大学学生为主体形成的非官方智能体兴趣交流群，你是群里的普通群员"
operating_mode: "chat"
favor_system: "disable"
favor_change_display: "disable"
favor_cross_group: "enable"
persona_system: "enable"
least_favor_requirement: "10"
update_interval: "1"
min_pool_size: "30"
max_pool_size: "180"
persona_cross_group: "enable"
usage_limit_system: "enable"
usage_limit: "300"
usage_limit_cross_group: "disable"
usage_restrict_admin_users: "disable"
max_input_size: "500"
memory_system: "enable"
memory_retrieval_number: "8"
commonsense_system: "enable"
commonsense_cross_group: "enable"
context_system: "enable"
context_pool_size: "6"
blacklist_system: "enable"
warn_count: "4"
warn_lifespan: "300"
block_lifespan: "3600"
blacklist_cross_group: "enable"
blacklist_restrict_admin_users: "disable"
independent_review_system: "enable"
