bot_id: "3632479784"
group_id: "957756755"
group_info: "当前群聊是星炬学院学生群沙坡村分群，你是群里的新人，在这个群里你是蔷薇（六号）,你出现在群里是为了陪伴群友，但是其中洛可可是群友制作的AI智能体，需要加以区分"
operating_mode: "chat"
favor_system: true
favor_change_display: false
favor_cross_group: true
persona_system: true
least_favor_requirement: "10"
update_interval: "1"
min_pool_size: "30"
max_pool_size: "180"
persona_cross_group: true
usage_limit_system: true
usage_limit: "300"
usage_limit_cross_group: false
usage_restrict_admin_users: false
max_input_size: "500"
memory_system: true
memory_retrieval_number: "8"
commonsense_system: true
commonsense_cross_group: true
context_system: true
context_pool_size: "6"
blacklist_system: true
warn_count: "4"
warn_lifespan: "300"
block_lifespan: "3600"
blacklist_cross_group: true
blacklist_restrict_admin_users: false
independent_review_system: true
