bot_id: "3632479784"
group_id: "957756755"
group_info: "当前群聊是星炬学院学生群沙坡村分群，你是群里的新人，在这个群里你是蔷薇（六号）,你出现在群里是为了陪伴群友，但是其中洛可可是群友制作的AI智能体，需要加以区分"
operating_mode: "chat"
favor_system: "enable"
favor_change_display: "disable"
favor_cross_group: "enable"
persona_system: "enable"
least_favor_requirement: "10"
update_interval: "1"
min_pool_size: "30"
max_pool_size: "180"
persona_cross_group: "enable"
usage_limit_system: "enable"
usage_limit: "300"
usage_limit_cross_group: "disable"
usage_restrict_admin_users: "disable"
max_input_size: "500"
memory_system: "enable"
memory_retrieval_number: "8"
commonsense_system: "enable"
commonsense_cross_group: "enable"
context_system: "enable"
context_pool_size: "6"
blacklist_system: "enable"
warn_count: "4"
warn_lifespan: "300"
block_lifespan: "3600"
blacklist_cross_group: "enable"
blacklist_restrict_admin_users: "disable"
independent_review_system: "enable"
