- bot_id: "这里是智能体QQ号"
  group_id: "这里是该配置应用的群号"
  group_info: "这里填写当前群聊的基本信息，比如群名称、成员身份等"
  operating_mode: "chat"
  favor_system: "enable"
  favor_change_display: "disable"
  favor_cross_group: "enable"
  persona_system: "disable"
  persona_cross_group: "enable"
  usage_limit_system: "enable"
  usage_limit: "300"
  usage_limit_cross_group: "disable"
  usage_restrict_admin_users: "disable"
  max_input_size: "500"
  memory_system: "disable"
  memory_retrieval_number: "8"
  commonsense_system: "enable"
  commonsense_cross_group: "disable"
  context_system: "enable"
  context_pool_size: "8"
  blacklist_system: "enable"
  warn_count: "4"
  warn_lifespan: "300"#单次警告的生命周期，秒为单位
  block_lifespan: "3600"#屏蔽时长，秒为单位
  blacklist_cross_group: "enable"
  blacklist_restrict_admin_users: "disable"
  independent_review_system: "disable"
